In [9]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\David\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\David\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\David\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\David\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\David\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [10]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv('IMDB-Movie-Data.csv')

In [16]:
df.head(5)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Rating_original,Votes_original,imdb_id
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.0,1385299,333.13,76.0,8.1,757074,tt2015381
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,707518,126.46,65.0,7.0,485820,tt1446714
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,631421,138.12,62.0,7.3,157606,tt4972582
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.1,217014,270.32,59.0,7.2,60545,tt3470600
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,5.9,767048,325.02,40.0,6.2,393727,tt1386697

In [17]:
df.tail(5)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Rating_original,Votes_original,imdb_id
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.3,55390,NaN,45.0,6.2,27585,tt1741273
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,103101,17.54,46.0,5.5,73152,tt0498353
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,91674,58.01,50.0,6.2,70699,tt1023481
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,8575,NaN,22.0,5.6,4881,tt2758904
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,26086,19.64,11.0,5.3,12435,tt4383594

In [15]:
df.dtypes

Rank                    int64
Title                     str
Genre                     str
Description               str
Director                  str
Actors                    str
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
Rating_original       float64
Votes_original          int64
imdb_id                   str
dtype: object

In [19]:
df.columns.values

<StringArray>
[              'Rank',              'Title',              'Genre',
        'Description',           'Director',             'Actors',
               'Year',  'Runtime (Minutes)',             'Rating',
              'Votes', 'Revenue (Millions)',          'Metascore',
    'Rating_original',     'Votes_original',            'imdb_id']
Length: 15, dtype: str

In [20]:
df.describe()

,Rank,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Rating_original,Votes_original
count,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,872.000000,936.000000,1000.000000,1.000000e+03
mean,500.500000,2012.783000,113.172000,6.682300,2.820773e+05,82.956376,58.985043,6.723200,1.698083e+05
std,288.819436,3.205962,18.810908,0.917103,3.243042e+05,103.253540,17.194757,0.945429,1.887626e+05
min,1.000000,2006.000000,66.000000,1.900000,1.550000e+02,0.000000,11.000000,1.900000,6.100000e+01
25%,250.750000,2010.000000,100.000000,6.200000,7.249050e+04,13.270000,47.000000,6.200000,3.630900e+04
50%,500.500000,2014.000000,111.000000,6.700000,1.835560e+05,47.985000,59.500000,6.800000,1.107990e+05
75%,750.250000,2016.000000,123.000000,7.300000,3.646990e+05,113.715000,72.000000,7.400000,2.399098e+05
max,1000.000000,2016.000000,191.000000,9.100000,3.228950e+06,936.630000,100.000000,9.000000,1.791916e+06